Feature/controller create article
Crewder/gowiki-api pull request #17
Opened 2021-02-14 18:01 UTC by Rcoufourier

Pour le moment les user sont entrer manuellement.
Évolution ? => récupérer l'utilisateur connecté ?

2021-02-15 19:50 UTC, Camille-Arsac reviewed
Alors un peu violent de push direct sur la main :sweat_smile: . On va passer par la dev avant je pense que c'est mieux. Tu peux modifier ton Pull Request du coup stp ? Et attention je pense que tu vas avoir des conflits sur le readme car Florian à fait des modifs dessus. Sinon c'est cool ce que tu as fait :smile:

2021-02-15 19:50 UTC, Camille-Arsac commented on README.md
> +## Création d'un article
Update le readme en même temps comme ça se sera plus facile à faire la documentation et aussi pour que l'on puisse tester facilement :)

2021-02-15 20:58 UTC, Leroy-Florian commented
Évolution ? => récupérer l'utilisateur connecté ?
Le plus simple va être je pense de passé via le cookie. Dans le token JWT il y aura les info de la personne connecté

2021-02-20 21:18 UTC, Camille-Arsac requested changes

2021-02-20 21:18 UTC, Camille-Arsac commented on README.md
> +http://localhost/article
Tu pourrais rajouter le port dans ton url (:8080) stp :)

2021-02-20 21:18 UTC, Camille-Arsac commented on README.md
> +|content| string| contenu de l'article. Required |
Tu as commencé en français tu pourrais mettre aussi les required en français ;)

2021-02-20 21:18 UTC, Camille-Arsac commented on controllers/articles.go
>  	w.WriteHeader(http.StatusOK)
Comme du coup ici c'est une création il faudrait renvoyer le code 201 soit la constante `StatusCreated`

2021-02-20 21:18 UTC, Camille-Arsac commented on controllers/articles.go
> +	fmt.Fprint(w, &article)
Cette ligne n'a pas d'utilité, il me semble :)

2021-02-20 21:18 UTC, Camille-Arsac commented on main.go
> +	router.Methods("POST").Path("/article").Name("create").HandlerFunc(controllers.ArticleCreate)
J'aurais mis /article/create pour être plus clair :)

2021-02-20 21:19 UTC, Camille-Arsac commented
@Rcoufourier ça marche bien pour moi, c'est cool ce que tu as fait :)

2021-02-22 19:06 UTC, Camille-Arsac commented
Pour moi c'est tout ok avec ses retours !

2021-02-23 19:16 UTC, merged